#import "../fragments/current-user.gql"

query CURRENT_USER_QUERY {
  me {
    token
    currentUser {
      ...CurrentUser
    }
  }
}

subscription CURRENT_USER_SUBSCRIPTION {
  me {
    token
    currentUser {
      ...CurrentUser
    }
  }
}

mutation REFRESH_TOKEN_MUTATION {
  refresh {
    token
  }
}


mutation REFRESH_COOKIES_MUTATION($token: String!) {
  refreshCookies(token: $token) {
    token
  }
}
